name: lschule
favicon: null
layout_spectrum: 0.8500867879483849
typography_spectrum: 0.10685082734562457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5958814392797649
  lightness: 0.5830113266129047
  saturation: 0.7947903606109321
  rhythmicContrast: 0.125747948884964
purpose: []
