name: lschule
favicon: null
layout_spectrum: 0.98536
typography_spectrum: 0.25563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#152562'
    - '#bec59f'
    - '#828783'
    - '#c32968'
  brandStrength: 0.5958814392797649
  lightness: 0.5830113266129047
  saturation: 0.7947903606109321
  rhythmicContrast: 0.75
purpose: []
