purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#44690f'
    - '#d7d15e'
    - '#9f8571'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
name: lschule
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5042553
layout_spectrum: 0.1851064
